export enum UserEnum {
  DRIVER = 'DRIVER',
  VETERINARIAN = 'VETERINARIAN',
  SHELTER_ADMIN = 'SHELTER_ADMIN',
  MANAGER = 'MANAGER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  FOSTER = 'FOSTER',
  FOSTER_ADMIN = 'FOSTER_ADMIN',
}
