export enum DocumentTypeEnum {
  FOSTER_AGREEMENT = 'FOSTER_AGREEMENT',
  ID_CARD = 'ID_CARD',
  HOME_AUTHENTICATION = 'HOME_AUTHENTICATION',
  TRANSPORT_CERTIFICATE = 'TRANSPORT_CERTIFICATE',
  OTHER = 'OTHER',
}

export enum DocumentStatusEnum {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
